"""Presentation helpers for the docs/ pages that reproduce the study manuscript (version 10) and the extended
corpus of the pipeline.

`contenido_v10.json` is written by `export_docs_content.py` (revision 10), which runs the real document builder
with its writing methods intercepted: resolved text with numbered citations, tables, legends, equations and
references, in English and Spanish. The plates are generated by `figuras_principales.py` and
`figuras_suplementarias.py` from `data/`; this module only presents them.
"""
from pathlib import Path
from html import escape
import json
import re
import pandas as pd
from PIL import Image

HERE = Path(__file__).resolve().parent            # docs/study
REL = 'study'                                      # relative path from docs/*.qmd
CONTENT = json.loads((HERE / 'data' / 'contenido_v10.json').read_text(encoding='utf-8'))
LABELS = {
    'en': {'files': 'Plate files (175 mm, {dpi}): ', 'dpi': '300 dpi', 'dpi_static': '300 dpi, revision 09', 'eq': 'Eq. ', 'rows': 'rows'},
    'es': {'files': 'Archivos de la lámina (175 mm, {dpi}): ', 'dpi': '300 ppp', 'dpi_static': '300 ppp, revisión 09', 'eq': 'Ec. ', 'rows': 'filas'},
}


def events(doc, lang='en'):
    return CONTENT[lang][doc]


def html_table(title, columns, rows, kinds, notes, small=True):
    cls = 'table table-striped table-sm' if small else 'table table-striped'
    out = [f'<div class="analysis-table" role="region" tabindex="0"><table class="{cls}">',
           f'<caption>{title}</caption>', '<thead><tr>' + ''.join(f'<th>{escape(c)}</th>' for c in columns) + '</tr></thead><tbody>']
    for r, k in zip(rows, kinds):
        if k == 'group':
            out.append(f'<tr class="table-group"><td colspan="{len(columns)}"><b>{escape(r[0])}</b></td></tr>')
        else:
            out.append('<tr>' + ''.join(f'<td>{escape(str(v))}</td>' for v in r) + '</tr>')
    out.append('</tbody></table>')
    if notes:
        out.append(f'<p class="table-note">{notes}</p>')
    out.append('</div>')
    return '\n'.join(out)


def figure_md(fig_id, lang, title, caption):
    preview = f'{REL}/qa/Figure_{fig_id}_{lang}_preview.png'
    exts = ('png', 'pdf') if fig_id in ('S1', 'S6') else ('png', 'svg', 'pdf')     # S1 and S6: inherited plates without SVG
    links = ' · '.join(f'[{ext.upper()}]({REL}/figures/{lang}/Figure_{fig_id}.{ext})' for ext in exts)
    cap = f'**{escape(title)}** {escape(caption)}'
    lab = LABELS[lang]
    files = lab['files'].format(dpi=lab['dpi'] if fig_id not in ('S1', 'S6') else lab['dpi_static'])
    return (f'![{cap}]({preview}){{fig-align="center" width="100%"}}\n\n'
            f'<p class="fig-links">{files}{links}</p>')


def equation_html(e, lang):
    imgs = []
    for rel in e['images']:
        with Image.open(HERE / rel) as im:
            w = round(im.width / 600 * 96 * 10 / 15)      # composed at 15 pt and 600 dpi, printed at 10 pt
        imgs.append(f'<img src="{REL}/{rel}" width="{w}" alt="{escape(e["label"])}">')
    num = LABELS[lang]['eq'] + str(e['number'])
    return (f'<div class="equation"><div class="eq-label">{escape(e["label"])}</div>'
            f'<div class="eq-row"><div class="eq-body">{"<br>".join(imgs)}</div><div class="eq-num">{num}</div></div></div>')


def render(doc, lang='en', skip_title=True, heading_shift=1):
    """Markdown (with embedded HTML) of the exported document, in the order of the DOCX."""
    out = []
    for e in events(doc, lang):
        k = e['kind']
        if k == 'title':
            if not skip_title:
                out.append('## ' + e['html'])
        elif k in ('h1', 'h2', 'h3'):
            level = int(k[1]) + heading_shift
            out.append('#' * level + ' ' + e['html'])
        elif k == 'p':
            out.append(e['html'])
        elif k == 'ric_start':
            out.append('::: {.research-context}')
        elif k == 'ric_end':
            out.append(':::')
        elif k == 'table':
            out.append(html_table(e['title'], e['columns'], e['rows'], e['kinds'], e['notes']))
        elif k == 'figure':
            out.append(figure_md(e['id'], lang, e['title'], e['caption']))
        elif k == 'equation':
            out.append(equation_html(e, lang))
        elif k == 'references':
            out.append('#' * (1 + heading_shift) + ' ' + e['title'])
            out.append('\n'.join(f'{it["n"]}. {escape(it["text"])}' for it in e['items']))
    return '\n\n'.join(out)


def summary_counts(doc, lang='en'):
    ev = events(doc, lang)
    return {'paragraphs': sum(e['kind'] == 'p' for e in ev), 'tables': sum(e['kind'] == 'table' for e in ev),
            'figures': sum(e['kind'] == 'figure' for e in ev), 'equations': sum(e['kind'] == 'equation' for e in ev),
            'references': sum(len(e['items']) for e in ev if e['kind'] == 'references')}


# ------------------------------------------------------------------ extended corpus (version 02, without Rett, English)
CORPUS = HERE / 'corpus'
GROUP_LABELS = {
    'Láminas suplementarias centrales del artículo': 'Core supplementary plates of the article',
    'Episodios hospitalarios en detalle': 'Hospital episodes in detail',
    'Ruta administrativa REM agregada en detalle': 'Aggregate REM administrative pathway in detail',
    'Análisis espacial y correlación territorial': 'Spatial analysis and territorial correlation',
    'Denominadores, encuestas y educación': 'Denominators, surveys and education',
    'Razón por sexo entre fuentes': 'Sex ratio across sources',
    'Diagnósticos de los modelos y sensibilidad a la definición de caso': 'Model diagnostics and case-definition sensitivity',
    'Fuentes y flujo de datos': 'Sources and data flow',
    'Metodología extendida': 'Extended methods',
    'Tablas suplementarias centrales del artículo': 'Core supplementary tables of the article',
    'Tablas de datos completas e inventario del proyecto': 'Complete data tables and project inventory',
}


def corpus_captions():
    return json.loads((CORPUS / 'captions.json').read_text(encoding='utf-8'))


def corpus_titles():
    return json.loads((CORPUS / 'titles.json').read_text(encoding='utf-8'))


def corpus_figure_md(stem, cap):
    title = cap.get('title', stem); caption = cap.get('caption', '')
    return (f'![**{escape(title)}** {escape(caption)}]({REL}/corpus/figures/{stem}.jpg){{fig-align="center" width="100%"}}')


def corpus_table_html(stem, meta):
    df = pd.read_csv(CORPUS / 'tables' / f'{stem}.csv', dtype=str, keep_default_na=False)
    title = meta.get('title', stem); note = meta.get('note', '')
    table = df.to_html(index=False, escape=True, border=0, classes='table table-striped table-sm')
    return (f'<details class="corpus-table"><summary><b>{escape(title)}</b> <span class="muted">({stem}.csv; {len(df)} rows)</span></summary>'
            f'<div class="analysis-table" role="region" tabindex="0">{table}</div>'
            + (f'<p class="table-note">{escape(note)}</p>' if note else '') + '</details>')


def corpus_index():
    """Order and thematic groups of the module-17 index (`extended_material_index.md`, written in Spanish);
    identifiers and group names are returned in English."""
    rows = {'article_figures': [], 'article_tables': [], 'figures': [], 'tables': []}
    for line in (CORPUS / 'extended_material_index.md').read_text(encoding='utf-8').splitlines():
        if not line.startswith('| '):
            continue
        cells = [c.strip() for c in line.strip().strip('|').split('|')]
        m = re.match(r'(Figura|Tabla) (S?\d+)$', cells[0])
        if not m:
            continue
        kind = m.group(1)
        ident = ('Figure ' if kind == 'Figura' else 'Table ') + m.group(2)
        if len(cells) == 3:
            rows['article_figures' if kind == 'Figura' else 'article_tables'].append(
                {'id': ident, 'file': cells[1].strip('`'), 'desc': cells[2]})
        elif len(cells) == 5:
            rows['figures' if kind == 'Figura' else 'tables'].append(
                {'id': ident, 'group': GROUP_LABELS.get(cells[1], cells[1]), 'file': cells[2].strip('`'), 'origin': cells[3], 'desc': cells[4]})
    return rows


def corpus_lookup(stem, main, extra, fallback_id, fallback_desc, key='title'):
    meta = main.get(stem) or extra.get(stem) or {}
    if not meta.get(key):
        meta = dict(meta); meta[key] = f'{fallback_id}. {fallback_desc}'
    return meta


# ------------------------------------------------------------------ version registry
# `versions.json` records what each manuscript version added to the results. Its counts come from
# `scripts/audit_versions.py`, which hashes every tidy table, so the pages below cannot drift from
# the audit: they are rendered from the registry rather than written by hand.
REGISTRY = json.loads((HERE / 'versions.json').read_text(encoding='utf-8'))


def versions():
    """Every version of the series, in chronological order."""
    return REGISTRY['versions']


def version(vid):
    """One version by its two-digit id."""
    return next(v for v in REGISTRY['versions'] if v['id'] == vid)


def audit_note():
    """The finding of the table-level audit, for pages that need to state it."""
    return REGISTRY['audit']['finding']


def version_rows_html():
    """The index table: one row per version, saying what it added and where its results are."""
    head = ('<thead><tr><th>Version</th><th>Date</th><th>What it is</th>'
            '<th>Tidy tables</th><th>Results</th></tr></thead>')
    rows = []
    for v in versions():
        same = v.get('identical_results_to')
        tables = str(v['tidy_tables']) if v['tidy_tables'] else '—'
        if same:
            tables += f' <span class="same-as">= v{same}</span>'
        name = f"v{v['id']} · {escape(v['title'])}"
        link = f'<a href="{v["page"]}">{name}</a>' if v.get('page') else name
        rows.append(f'<tr><td>{link}</td><td>{v["date"]}</td><td>{escape(v["what"])}</td>'
                    f'<td class="num">{tables}</td><td>{escape(v["results"])}</td></tr>')
    return f'<table class="version-index">{head}<tbody>{"".join(rows)}</tbody></table>'


def figure_files(stem, lang='en'):
    """Links to the exported formats of one plate, skipping formats that were not produced."""
    out = []
    for ext in ('png', 'svg', 'pdf'):
        if (HERE / 'figures' / lang / f'{stem}.{ext}').exists():
            out.append(f'[{ext.upper()}]({REL}/figures/{lang}/{stem}.{ext})')
    return ' · '.join(out)


def data_tables():
    """The public tidy tables the site ships, with their size, so a page can list what it reproduces from."""
    out = []
    for p in sorted((HERE / 'data').glob('*.csv')):
        with p.open(encoding='utf-8', errors='replace') as fh:
            rows = sum(1 for _ in fh) - 1
        out.append({'name': p.name, 'rows': max(rows, 0), 'kb': round(p.stat().st_size / 1024, 1)})
    return out
