project:
  type: default
  execute-dir: project
  render:
    - index.qmd
    - metodologia.qmd
    - rem.qmd
    - grd.qmd

lang: es
jupyter: python3
date: today
format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 3
    toc-location: right
    embed-resources: true
    css: styles.css
    code-fold: true
    code-summary: "Ver Python"
    fig-cap-location: bottom
    number-sections: false
    smooth-scroll: true
execute:
  echo: false
  error: false
  warning: false
  cache: false
  daemon: false
