project:
  type: default
  execute-dir: project
  render:
    - manuscript.qmd

lang: es
bibliography: ../docs/references.bib
csl: vancouver.csl
link-citations: false
format:
  docx:
    toc: false
    number-sections: true
    fig-dpi: 300
    fig-width: 6.5
    fig-height: 5
    fig-cap-location: bottom
    tbl-cap-location: top
execute:
  echo: false
  warning: false
  error: false
  cache: false
  daemon: false
